src/Entity/Invoice.php
<?php

namespace Tigris\InvoiceBundle\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use JMS\Serializer\Annotation as JMS;
use Symfony\Component\Validator\Constraints as Assert;
use Tigris\BaseBundle\Entity\Model\User;
use Tigris\InvoiceBundle\Invoice\Calculator;
use Tigris\InvoiceBundle\Invoice\InvoiceItem;
use Tigris\InvoiceBundle\Repository\InvoiceRepository;

#[ORM\Entity(repositoryClass: InvoiceRepository::class)]
#[ORM\Table(name: 'invoice')]
class Invoice
{
    use SoftDeleteableEntity;
    use TimestampableEntity;

    final public const STATUS_NEW = 'new';
    final public const STATUS_FINISHED = 'finished';
    final public const STATUS_CANCELED = 'canceled';
    final public const STATUS_AWAITING_PAYMENT = 'awaiting_payment';
    final public const STATUS_PAID = 'paid';
    final public const STATUS_READY = 'ready';
    final public const STATUS_SHIPPED = 'shipped';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int|null $id = null;

    #[ORM\Column(length: 180)]
    #[Assert\NotBlank]
    private string $name;

    #[ORM\Column(length: 30)]
    private string $status = self::STATUS_NEW;

    #[ORM\Column(length: 30)]
    private string $paymentStatus = self::STATUS_AWAITING_PAYMENT;

    #[ORM\Column(length: 30)]
    private string $shippingStatus = self::STATUS_READY;

    #[ORM\Column]
    #[Assert\NotBlank]
    private int $number = 0;

    #[ORM\Column(nullable: true)]
    private string|null $numberPrefix = null;

    #[ORM\Column(type: Types::JSON)]
    private array $items = [];

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private string|null $vendorAddress = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private string|null $shippingAddress = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private string|null $billingAddress = null;

    #[ORM\ManyToOne(cascade: ['all'])]
    private Customer $customer;

    #[JMS\AccessType(type: 'public_method')]
    private float $amountET = 0.0;

    #[JMS\AccessType(type: 'public_method')]
    private float $amountIT = 0.0;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private string|null $message = null;

    #[ORM\Column(nullable: true)]
    private float|null $discount = null;

    #[ORM\Column(nullable: true)]
    private string|null $discountType = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private \DateTimeInterface $date;

    #[ORM\ManyToOne]
    private Model|null $model = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private User|null $author = null;

    public function __construct()
    {
        $this->date = new \DateTime();
    }

    public function getId(): int|null
    {
        return $this->id;
    }

    public function getNumber(): int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getVendorAddress(): string
    {
        return $this->vendorAddress ?? '';
    }

    public function setVendorAddress(string $vendorAddress): self
    {
        $this->vendorAddress = $vendorAddress;

        return $this;
    }

    public function getShippingAddress(): string
    {
        return $this->shippingAddress ?? '';
    }

    public function setShippingAddress(string $shippingAddress): self
    {
        $this->shippingAddress = $shippingAddress;

        return $this;
    }

    public function getBillingAddress(): string
    {
        return $this->billingAddress ?? '';
    }

    public function setBillingAddress(string $billingAddress): self
    {
        $this->billingAddress = $billingAddress;

        return $this;
    }

    public function getCustomer(): Customer|null
    {
        return $this->customer;
    }

    public function setCustomer(Customer $customer = null): self
    {
        $this->customer = $customer;

        return $this;
    }

    public function getAmountET(): float
    {
        $total = 0;

        foreach ($this->items as $item) {
            $amount = $item['amountET'];
            $total += ($amount * (int) $item['quantity']);
        }

        return $total;
    }

    public function getTaxAmount()
    {
        $taxes = [];
        foreach ($this->items as $item) {
            foreach ($item['taxes'] as $name => $value) {
                $taxId = $name . ' ' . $value . '%';
                if (!isset($taxes[$taxId])) {
                    $taxes[$taxId] = 0;
                }
                // PRIXTTC*100/(100+TVA)
                $taxes[$taxId] += Calculator::amountIT($item['amountET'], $value);
            }
        }

        return $taxes;
    }

    public function setAmountET(float $amountET): self
    {
        $this->amountET = $amountET;

        return $this;
    }

    public function setAmountIT(float $value): self
    {
        return $this;
    }

    public function getAmountIT(): float
    {
        $total = 0;

        foreach ($this->items as $item) {
            $amount = $item['amountIT'] ?? $item['amountET'];
            $total += ($amount * (int) $item['quantity']);
        }

        return $total;
    }

    public function getItems(): array
    {
        return $this->items;
    }

    public function setItems(array $items): self
    {
        if (is_string($items)) {
            $items = json_decode($items, null, 512, JSON_THROW_ON_ERROR);
        }
        $this->items = $items;

        return $this;
    }

    public function addItem($item): self
    {
        if ($item instanceof InvoiceItem) {
            $item = $item->toArray();
        } elseif (is_string($item)) {
            $item = json_decode($item, null, 512, JSON_THROW_ON_ERROR);
        }

        $this->items[] = $item;

        return $this;
    }

    public function getTotal(): float
    {
        return Calculator::totalIT($this->items);
    }

    public function getMessage(): string
    {
        return $this->message ?? '';
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getDiscount(): float
    {
        return $this->discount ?? 0.0;
    }

    public function setDiscount(float $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    public function getDiscountType(): string|null
    {
        return $this->discountType;
    }

    public function setDiscountType(string|null $discountType): self
    {
        $this->discountType = $discountType;

        return $this;
    }

    public function getDate(): \DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getModel(): Model|null
    {
        return $this->model;
    }

    public function setModel(Model $model = null): self
    {
        $this->model = $model;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status ?? static::STATUS_NEW;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPaymentStatus(): string
    {
        return $this->paymentStatus ?? static::STATUS_AWAITING_PAYMENT;
    }

    public function setPaymentStatus(string $paymentStatus): self
    {
        $this->paymentStatus = $paymentStatus;

        return $this;
    }

    public function getShippingStatus(): string
    {
        return $this->shippingStatus ?? static::STATUS_READY;
    }

    public function setShippingStatus(string $shippingStatus): self
    {
        $this->shippingStatus = $shippingStatus;

        return $this;
    }

    #[JMS\VirtualProperty]
    public function getNumberStr(): string
    {
        return $this->numberPrefix . str_pad($this->number, 6, '0', STR_PAD_LEFT);
    }

    public function getAuthor(): User|null
    {
        return $this->author;
    }

    public function setAuthor(User $author = null): self
    {
        $this->author = $author;

        return $this;
    }

    public function getNumberPrefix(): string
    {
        return $this->numberPrefix ?? '';
    }

    public function setNumberPrefix(string $numberPrefix = null): self
    {
        $this->numberPrefix = $numberPrefix;

        return $this;
    }

    #[JMS\VirtualProperty()]
    public function isLocked(): bool
    {
        return self::STATUS_FINISHED === $this->status;
    }
}

src/Controller/Admin/InvoiceController.php
<?php

namespace Tigris\InvoiceBundle\Controller\Admin;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Contracts\Translation\TranslatorInterface;
use Tigris\BaseBundle\Controller\Admin\BaseController;
use Tigris\BaseBundle\Repository\UserRepository;
use Tigris\BaseBundle\Traits\FormTrait;
use Tigris\InvoiceBundle\Entity\Invoice;
use Tigris\InvoiceBundle\Form\Type\InvoiceType;
use Tigris\InvoiceBundle\Manager\InvoiceManager;
use Tigris\InvoiceBundle\Repository\InvoiceRepository;

#[Route('/admin/invoice')]
#[IsGranted('ROLE_ADMIN')]
class InvoiceController extends BaseController
{
    use FormTrait;

    #[Route('/index')]
    public function index(UserRepository $userRepository): Response
    {
        $this->generateBreadcrumbs([
            'menu.invoices' => ['route' => 'tigris_invoice_admin_invoice_index'],
        ]);

        $user = $userRepository->findBy(['enabled' => true]);

        return $this->render("@TigrisInvoice\admin\invoice\index.html.twig", [
            'users' => $user,
        ]);
    }

    #[Route('/data', options: ['expose' => 'admin'])]
    public function data(Request $request, InvoiceRepository $invoiceRepository): Response
    {
        $criteria = $this->getCriteria($request);
        $criteria['status'] = $request->query->get('status', '');
        $criteria['payment_status'] = $request->query->get('paymentStatus', '');
        $criteria['shipping_status'] = $request->query->get('shippingStatus', '');
        $criteria['user'] = $request->query->get('user', '');

        $data = $invoiceRepository->findData($criteria);

        return $this->paginatorToJsonResponse($data);
    }

    #[Route('/new', options: ['expose' => 'admin'], methods: ['GET', 'POST'])]
    public function new(
        Request $request, 
        TranslatorInterface $translator, 
        InvoiceManager $invoiceManager, 
        EntityManagerInterface $em
    ): Response
    {
        $this->generateBreadcrumbs([
            'menu.invoices' => ['route' => 'tigris_invoice_admin_invoice_index'],
            'invoice.add.add' => ['route' => 'tigris_invoice_admin_invoice_new'],
        ]);

        $entity = $invoiceManager->create();

        $form = $this->createForm(InvoiceType::class, $entity, [
            'method' => Request::METHOD_POST,
            'action' => $this->generateUrl('tigris_invoice_admin_invoice_new'),
        ]);
        $this->addFormActions($form, $this->generateUrl('tigris_invoice_admin_invoice_index'));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($entity);
            $em->flush();

            $this->addFlash(
                'success',
                $translator->trans('invoice.edit.success')
            );

            return $this->redirectToRoute('tigris_invoice_admin_invoice_index');
        }

        return $this->render('@TigrisInvoice\admin\invoice\new.html.twig', ['form' => $form, 'entity' => $entity]);
    }

    #[Route('/{id}/edit', requirements: ['id' => '\d+'], options: ['expose' => 'admin'], methods: ['GET', 'PUT'])]
    public function edit(
        Request $request, 
        Invoice $entity, 
        TranslatorInterface $translator, 
        EntityManagerInterface $em
    ): Response
    {
        $form = $this->createForm(InvoiceType::class, $entity, [
            'method' => Request::METHOD_PUT,
            'action' => $this->generateUrl('tigris_invoice_admin_invoice_edit', ['id' => $entity->getId()]),
        ]);
        $this->addFormActions($form, $this->generateUrl('tigris_invoice_admin_invoice_index'));

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($entity);
            $em->flush();

            $this->addFlash(
                'success',
                $translator->trans('invoice.edit.success')
            );

            return $this->redirectToRoute('tigris_invoice_admin_invoice_index');
        }

        return $this->render('@TigrisInvoice\admin\invoice\edit.html.twig', ['form' => $form, 'entity' => $entity]);
    }

    #[Route('/{id}/remove', requirements: ['id' => '\d+'], options: ['expose' => 'admin'], methods: ['GET', 'DELETE'])]
    public function delete(
        Request $request, 
        Invoice $entity, 
        TranslatorInterface $translator, 
        EntityManagerInterface $em
    ): Response
    {
        $form = $this->createFormBuilder($entity, [
            'method' => Request::METHOD_DELETE,
            'action' => $this->generateUrl('tigris_invoice_admin_invoice_remove', ['id' => $entity->getId()]),
        ])->getForm();
        $this->addFormActions($form, $this->generateUrl('tigris_invoice_admin_invoice_index'), 'button.delete');

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->remove($entity);
            $em->flush();

            $this->addFlash(
                'success',
                $translator->trans('invoice.delete.success')
            );

            return $this->redirectToRoute('tigris_invoice_admin_invoice_index');
        }

        return $this->render('@TigrisInvoice\admin\invoice\remove.html.twig', ['form' => $form, 'entity' => $entity]);
    }
}

src/Controller/InvoiceController.php
<?php

namespace Tigris\InvoiceBundle\Controller;

use Dompdf\Dompdf;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Tigris\BaseBundle\Controller\BaseController;
use Tigris\InvoiceBundle\Entity\Invoice;

#[Route('/invoice')]
#[IsGranted('ROLE_USER')]
class InvoiceController extends BaseController
{
    #[Route(
        path: '/{id}/show.{_format}', 
        requirements: ['id' => '\d+', '_format' => 'html|pdf'], 
        defaults: ['_format' => 'html'], 
        options: ['expose' => true]
    )]
    public function show(Invoice $entity, string $_format): Response
    {
        if ('pdf' === $_format) {
            $dompdf = new Dompdf();
            $dompdf->loadHtml($this->renderView('@TigrisInvoice/invoice/show.pdf.twig', [
                'entity' => $entity,
            ]));
            $dompdf->setPaper('A4', 'portrait');
            $dompdf->render();
            $dompdf->stream($entity->getName().'.pdf');

            return new Response('');
        }

        return $this->render('@TigrisInvoice/invoice/show.html.twig', [
            'entity' => $entity,
        ]);
    }
}

templates/invoice/show.html.twig
{% extends '@TigrisBase/layout.html.twig' %}
{% block main %}
    {% embed "@TigrisBase/decorators/_card.html.twig" %}
        {% block header %}
            <div class="d-flex justify-content-between">
                <div>
                {{ entity.name }}
                </div>
                <div>
                {{ entity.numberStr }}
                </div>
            </div>
        {% endblock %}

        {% block body %}
            <div>{{ entity.createdAt|format_datetime('full', 'short') }}</div>
            <hr/>
            <div class="d-flex justify-content-between">
                <div>
                    {{ entity.vendorAddress|raw }}
                </div>
                <div>
                    {{ entity.billingAddress|raw }}
                </div>
               
            </div>
            <hr/>

            <h2>{{ 'invoice.details'|trans }}</h2>
            {{ 'invoice.number'|trans }}: {{ entity.numberStr }}
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>{{ 'invoice.item.designation'|trans }}</th>
                        <th>{{ 'invoice.item.amount_et'|trans }}</th>
                        <th>{{ 'invoice.item.tax'|trans }}</th>
                        <th>{{ 'invoice.item.amount_it'|trans }}</th>
                        <th>{{ 'invoice.item.quantity'|trans }}</th>
                        <th>{{ 'invoice.item.total'|trans }}</th>
                    </tr>
                </thead>

                <tbody>
                    {% for item in entity.items %}
                    <tr>
                        <td>{{ item.designation }}</td>
                        <td>{{ item.amountET|format_currency('EUR') }}</td>
                        <td>{% if item.taxes is defined %}{% for name, tax in item.taxes %}
                        {{ name }} {{ tax }}%<br/>
                        {% endfor %}{% endif %}
                        </td>
                        <td>
                        {% if item.amountIT is defined %}
                        {{ item.amountIT|format_currency('EUR') }}
                        {% else %}
                        {{ item.amountET|format_currency('EUR') }}
                        {% endif %}
                        </td>
                        <td>{{ item.quantity }}</td>
                        <td>
                        {% if item.amountIT is defined %}
                        {{ (item.quantity * item.amountIT)|format_currency('EUR') }}
                        {% else %}
                        {{ (item.quantity * item.amountET)|format_currency('EUR') }}
                        {% endif %}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="5" class="text-right">{{ 'invoice.totalET'|trans }}</td>
                        <td><strong>{{ entity.amountET|format_currency('EUR') }}</strong></td>
                    </tr>
                    {% for name, value in entity.taxAmount %}
                    <tr>
                        <td colspan="5" class="text-right">{{ name }}</td>
                        <td>
                            {{ value|format_currency('EUR') }}
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="5" class="text-right"><strong>{{ 'invoice.total'|trans }}</strong></td>
                        <td><strong>{{ entity.amountIT|format_currency('EUR') }}</strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <a href="{{ path('tigris_invoice_invoice_show', {'id': entity.id, '_format': 'pdf'}) }}" class="btn btn-primary btn-print mt-2">{{ 'button.download'|trans|parse_icons }}</a>
        {% endblock %}
    {% endembed %}
{% endblock %}

templates/invoice/show.pdf.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
    .table {
        width:100%;
        border-collapse: collapse;
    }

    .addresses {
        width: 100%;
    }

    .addresses td {
        width: 50%;
    }

    .table td, .table th {
        padding: 0.75rem;
        vertical-align: top;
        text-align: left;
        border-top: 1px solid #dee2e6;
    }

    thead, thead th {
        background-color: #eaeaea;
    }
    </style>
</head>
<body>
    {% embed "@TigrisBase/decorators/_card.html.twig" %}
        {% block header %}
            <div class="">
                <div>
                {{ entity.name }}
                </div>
                <div>
                {{ entity.numberStr }}
                </div>
            </div>
        {% endblock %}

        {% block body %}
            <div>{{ entity.createdAt|format_datetime('full', 'short') }}</div>
            <hr/>
            <table class="addresses">
                <tr>
                    <td >
                    {{ entity.vendorAddress|raw }}
                    </td>
                    <td  style="text-align:right">
                    {{ entity.billingAddress|raw }}
                    </td>
                </tr>
            </table>
            <hr/>

            <h2>{{ 'invoice.details'|trans }}</h2>
            {{ 'invoice.number'|trans }}: {{ entity.numberStr }}
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>{{ 'invoice.item.designation'|trans }}</th>
                        <th>{{ 'invoice.item.amount_et'|trans }}</th>
                        <th>{{ 'invoice.item.tax'|trans }}</th>
                        <th>{{ 'invoice.item.amount_it'|trans }}</th>
                        <th>{{ 'invoice.item.quantity'|trans }}</th>
                        <th>{{ 'invoice.item.total'|trans }}</th>
                    </tr>
                </thead>

                <tbody>
                    {% for item in entity.items %}
                    <tr>
                        <td>{{ item.designation }}</td>
                        <td>{{ item.amountET|format_currency('EUR') }}</td>
                        <td>{% if item.taxes is defined %}{% for name, tax in item.taxes %}
                        {{ name }} {{ tax }}%<br/>
                        {% endfor %}{% endif %}
                        </td>
                        <td>
                        {% if item.amountIT is defined %}
                        {{ item.amountIT|format_currency('EUR') }}
                        {% else %}
                        {{ item.amountET|format_currency('EUR') }}
                        {% endif %}
                        </td>
                        <td>{{ item.quantity }}</td>
                        <td>
                        {% if item.amountIT is defined %}
                        {{ (item.quantity * item.amountIT)|format_currency('EUR') }}
                        {% else %}
                        {{ (item.quantity * item.amountET)|format_currency('EUR') }}
                        {% endif %}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="5" style="text-align: right">{{ 'invoice.totalET'|trans }}</td>
                        <td><strong>{{ entity.amountET|format_currency('EUR') }}</strong></td>
                    </tr>
                    {% for name, value in entity.taxAmount %}
                    <tr>
                        <td colspan="5" style="text-align: right">{{ name }}</td>
                        <td>
                            {{ value|format_currency('EUR') }}
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="5" style="text-align: right"><strong>{{ 'invoice.total'|trans }}</strong></td>
                        <td><strong>{{ entity.amountIT|format_currency('EUR') }}</strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
        {% endblock %}
    {% endembed %}
</body>
</html>